[camera]
device = /dev/video0
width = 680
height = 480
framerate = 15
duration = 10

[encoding]
bitrate = 1200
speed_preset = ultrafast

[overlay]
text = AC Future
halign = right
valign = top
font_size = 20
# Vertical spacing to prevent overlap (in pixels)
text_ypad = 10
temp_ypad = 45
clock_ypad = 80



